# Generated by Django 3.1.7 on 2021-03-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('binaries', '0001_initial'), ('binaries', '0002_auto_20210308_1232'), ('binaries', '0003_auto_20210308_1403')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
